#!/bin/bash

adduser --system --no-create-home blur-monitor
addgroup blur-monitor

usermod -aG blur-monitor blur-monitor
usermod -aG shadow blur-monitor

if pidof systemd 2>/dev/null; then
    systemctl daemon-reload
    systemctl enable blur-monitor
    systemctl start blur-monitor
fi
