#!/bin/bash

adduser --system --no-create-home blur-monitor
addgroup blur-monitor

usermod -aG blur-monitor blur-monitor
usermod -aG shadow blur-monitor

systemctl daemon-reload
systemctl enable blur-monitor
systemctl start blur-monitor
